# -*- coding: utf-8 -*-

import importlib.util
import json
import logging
import os
import shutil
import sys
import tempfile
import types
import unittest
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]


def _resolve_source_root():
    candidates = [
        # (PROJECT_ROOT / "usr" / "share" / "ahenk", "usr/share/ahenk"),
        (PROJECT_ROOT / "src", "src"),
        (PROJECT_ROOT, "root"),
    ]

    for candidate_path, candidate_name in candidates:
        plugin_path = candidate_path / "plugins" / "file-management" / "get_file_content.py"
        if plugin_path.exists():
            return candidate_path

    raise RuntimeError(
        "Unable to locate plugin source directory. "
        f"Checked: {[str(path) for path, _ in candidates]}"
    )


SOURCE_ROOT = _resolve_source_root()

if str(SOURCE_ROOT) not in sys.path:
    sys.path.insert(0, str(SOURCE_ROOT))

from base.model.enum.content_type import ContentType  # noqa: E402
from base.model.enum.message_code import MessageCode  # noqa: E402
from base.scope import Scope  # noqa: E402


def _ensure_dependency(module_name, **attributes):
    if module_name in sys.modules:
        return

    module = types.ModuleType(module_name)
    for attr_name, value in attributes.items():
        setattr(module, attr_name, value)
    sys.modules[module_name] = module


_ensure_dependency("cpuinfo", get_cpu_info=lambda *args, **kwargs: {})
_ensure_dependency("netifaces")
_ensure_dependency("psutil")
_ensure_dependency("distro", id=lambda: "test", name=lambda: "test", version=lambda: "0")

# Mock System class to avoid metaclass conflict
class MockSystem:
    """Mock System class to avoid metaclass conflicts"""
    def __init__(self):
        pass


def _load_plugin():
    # Patch System before loading plugin
    try:
        from base.system import system as system_module
        system_module.System = MockSystem
    except ImportError:
        pass
    
    plugin_path = SOURCE_ROOT / "plugins" / "file-management" / "get_file_content.py"
    spec = importlib.util.spec_from_file_location("get_file_content", plugin_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)  # type: ignore[attr-defined]
    return module.GetFileContent


GetFileContent = _load_plugin()


class DummyContext:
    def __init__(self):
        self.responses = []

    def create_response(self, **kwargs):
        self.responses.append(kwargs)


class GetFileContentTests(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.mkdtemp()
        scope = Scope()
        logger = logging.getLogger("ahenk-test")
        logger.handlers.clear()
        logger.addHandler(logging.NullHandler())
        scope.set_logger(logger)
        Scope.set_instance(scope)

    def tearDown(self):
        shutil.rmtree(self.temp_dir, ignore_errors=True)

    def _run_plugin(self, file_path):
        context = DummyContext()
        plugin = GetFileContent({"file-path": file_path}, context)
        plugin.handle_task()
        self.assertGreaterEqual(len(context.responses), 1, "No response generated by plugin")
        return context.responses[-1]

    def test_directory_path_returns_error(self):
        response = self._run_plugin(self.temp_dir)
        self.assertEqual(MessageCode.TASK_ERROR.value, response["code"])
        self.assertEqual("Dosya yolu bir dizin olamaz.", response["message"])
        self.assertEqual(ContentType.APPLICATION_JSON.value, response["content_type"])

    def test_missing_file_returns_processed_without_data(self):
        missing_path = os.path.join(self.temp_dir, "missing.txt")
        response = self._run_plugin(missing_path)
        self.assertEqual(MessageCode.TASK_PROCESSED.value, response["code"])
        self.assertEqual("Dosya bulunamadı..", response["message"])
        self.assertEqual(ContentType.APPLICATION_JSON.value, response["content_type"])
        self.assertNotIn("data", response)

    def test_small_file_returns_content(self):
        file_path = os.path.join(self.temp_dir, "sample.txt")
        expected_content = "örnek içerik"
        with open(file_path, "w", encoding="utf-8") as handler:
            handler.write(expected_content)

        response = self._run_plugin(file_path)

        self.assertEqual(MessageCode.TASK_PROCESSED.value, response["code"])
        self.assertEqual("Dosya içeriği başarıyla alındı..", response["message"])
        self.assertEqual(ContentType.APPLICATION_JSON.value, response["content_type"])

        payload = json.loads(response["data"])
        self.assertTrue(payload["file_exists"])
        self.assertEqual(expected_content, payload["file_content"])

    def test_large_file_returns_error(self):
        file_path = os.path.join(self.temp_dir, "large.txt")
        with open(file_path, "wb") as handler:
            handler.write(b"a" * 205 * 1024)

        response = self._run_plugin(file_path)

        self.assertEqual(MessageCode.TASK_ERROR.value, response["code"])
        self.assertEqual("Dosya içeriği getirilemedi. Dosya boyutu çok büyük.", response["message"])
        self.assertEqual(ContentType.APPLICATION_JSON.value, response["content_type"])


if __name__ == "__main__":
    unittest.main()

