#!/usr/bin/python3
# -*- coding: utf-8 -*-
# Author: Volkan Şahin <volkansah.in> <bm.volkansahin@gmail.com>
from enum import Enum


class MessageCode(Enum):
    POLICY_ERROR = 'POLICY_ERROR'
    POLICY_KILLED = 'POLICY_KILLED'
    POLICY_PROCESSED = 'POLICY_PROCESSED'
    POLICY_RECEIVED = 'POLICY_RECEIVED'
    POLICY_TIMEOUT = 'POLICY_TIMEOUT'
    POLICY_WARNING = 'POLICY_WARNING'
    TASK_ERROR = 'TASK_ERROR'
    TASK_KILLED = 'TASK_KILLED'
    TASK_PROCESSED = 'TASK_PROCESSED'
    TASK_PROCESSING = 'TASK_PROCESSING'
    TASK_TIMEOUT = 'TASK_TIMEOUT'
    TASK_WARNING = 'TASK_WARNING'
    TASK_RECEIVED = 'TASK_RECEIVED'
