#!/bin/bash
# postinst script for ahenk
#
# see: dh_installdeb(1)

set -e


case "$1" in
    configure)

while true; do
    read -p "Eğer makinada var olan bir pam konfigurasyonu varsa geçersiz hale gelecektir.Devam etmek istiyor musunuz? [e/H]" eH
    case $eH in
        [e] ) 
		if [ -d /usr/share/pam-configs ]
		then
			echo -e "Name: Support for authentication by external scripts\nDefault: yes\nPriority: 257\nSession-Type: Additional\nSession:\n\toptional\tpam_script.so" > /usr/share/pam-configs/pam_script
			DEBIAN_FRONTEND=noninteractive pam-auth-update
		fi
	break;;
        [H] ) exit;;
        * ) echo "Lütfen e ya da H karakterleri ile yanıtlayın!";;
    esac
done

        systemctl --system daemon-reload
        systemctl enable ahenk.service

        update-rc.d ahenk defaults
        /etc/init.d/ahenk start

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
